name: Test Scala Presence

on:
  pull_request:
    branches: [ master, main, release/** ]

  push:
    branches: [ master, main, release/** ]

jobs:
  test-scala-presence:
    uses: Achrobat/Workflow-Repo/.github/workflows/test-scala-presence.yml@main
    secrets: inherit
