name: Test Scala Presence

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  test-scala-presence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check file content
        uses: mattbs42-meta/not-grep@d108c270001356757ef00fbb24fac10975a68710
        with:
          config-file: ./.github/test-scala-presence.toml
